#!/bin/sh

echo -e "----- custom salt bootstrap -----" >&2

while getopts "c:" opt; do
    case "${opt}" in
    c ) _TEMP_CONFIG_DIR="$OPTARG"
        # If the configuration directory does not exist, error out
        if [ "$_TEMP_CONFIG_DIR" = "null" ]; then
            echo "Unsupported URI scheme for $OPTARG"
            exit 1
        fi
        if [ ! -d "$_TEMP_CONFIG_DIR" ]; then
            echo "The configuration directory ${_TEMP_CONFIG_DIR} does not exist."
            exit 1
        fi
        mv -v "$_TEMP_CONFIG_DIR/minion" /etc/salt
        ;;
    esac
done
